### ISSUE TITLE
Settings for windows 7

### ISSUE THREAD

**Issue by gegemon2012** [Nummer/Destroy-Windows-10-Spying#137] opened 2015-10-25 09:36 UTC
Please tell me why on Windows 7 x64 is not active upper seven points in the settings? They have developed specific for Windows 10? I would also like to know whether your program disables authentication windows and a like. If not, you can make it through the hosts by adding lines such as:
 127.0.0.1 mpa.one.microsoft.com
127.0.0.1 sls.microsoft.com
127.0.0.1 genuine.microsoft.com
127.0.0.1 wat.microsoft.com
127.0.0.1 mpa.microsoft.com
127.0.0.1 go.microsoft.akadns.com
![default](https://cloud.githubusercontent.com/assets/15074580/10714929/ee011f3e-7b14-11e5-8823-44ed1d4c92b9.JPG)

**Comment by mikhaelkh** [comment] 2015-10-25 11:10
Duplicate of #105

**Closed** 2015-10-25 19:07 UTC
